const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  docsSidebar: [
    {
      type: 'category',
      label: 'Introduction',
      collapsed: false,
      items: ['what-is-radicle', 'getting-started'],
    },
    {
      type: 'category',
      label: 'Understanding Radicle',
      collapsed: false,
      items: ['understanding-radicle/why-radicle', 'understanding-radicle/how-it-works', 'understanding-radicle/troubleshooting', 'understanding-radicle/glossary', 'understanding-radicle/faq']
    },
    {
      type: 'category',
      label: 'Get involved',
      collapsed: false,
      items: ['get-involved/join-the-community', 'get-involved/radicle-garden']
    }
  ],
};

module.exports = sidebars;