const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  docsSidebar: [
    'what-is-radicle',
    'migrate-github-radicle',
    'troubleshooting',
    {
      type: 'category',
      label: 'Code hosting',
      collapsed: false,
      items: [
        'using-radicle/create',
        'using-radicle/view-share',
        'using-radicle/push',
        'using-radicle/clone',
        'using-radicle/identity',
      ]
    },
    {
      type: 'category',
      label: 'Code collaboration',
      collapsed: false,
      items: [
        'using-radicle/collaboration',
        'using-radicle/issues',
        'using-radicle/track-review-merge',
      ]
    },
    {
      type: 'category',
      label: 'Understanding Radicle',
      collapsed: false,
      items: [
        'understanding-radicle/how-radicle-works',
        'understanding-radicle/radicle-versus-github-gitlab',
        'understanding-radicle/glossary',
        'understanding-radicle/faq',
      ]
    },
    {
      type: 'category',
      label: 'Get involved',
      collapsed: false,
      items: ['get-involved/join-the-community', 'get-involved/obtain-rad']
    }
  ],
};

module.exports = sidebars;
